name: Build Kyoga TV Android
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # This is the most stable version in 2026
        uses: ArtemSerebrennikov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          python_version: 3.10
          # We tell it exactly what to do here
          buildozer_command: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kyoga-TV-Android-App
          path: ./*.apk
